package com.example.lz.android_greendao_sample.external_dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.lz.android_greendao_sample.external_entity.SimpleExternalEntity;

import com.example.lz.android_greendao_sample.external_dao.SimpleExternalEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig simpleExternalEntityDaoConfig;

    private final SimpleExternalEntityDao simpleExternalEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        simpleExternalEntityDaoConfig = daoConfigMap.get(SimpleExternalEntityDao.class).clone();
        simpleExternalEntityDaoConfig.initIdentityScope(type);

        simpleExternalEntityDao = new SimpleExternalEntityDao(simpleExternalEntityDaoConfig, this);

        registerDao(SimpleExternalEntity.class, simpleExternalEntityDao);
    }
    
    public void clear() {
        simpleExternalEntityDaoConfig.getIdentityScope().clear();
    }

    public SimpleExternalEntityDao getSimpleExternalEntityDao() {
        return simpleExternalEntityDao;
    }

}
