package com.example.lz.android_greendao_sample.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.lz.android_greendao_sample.SimpleEntity;
import com.example.lz.android_greendao_sample.Province;
import com.example.lz.android_greendao_sample.City;
import com.example.lz.android_greendao_sample.CustomTypeEntity;
import com.example.lz.android_greendao_sample.KeepEntity;
import com.example.lz.android_greendao_sample.Person;
import com.example.lz.android_greendao_sample.PersonInfo;
import com.example.lz.android_greendao_sample.CustomerEntity;
import com.example.lz.android_greendao_sample.OrderEntity;
import com.example.lz.android_greendao_sample.Student;
import com.example.lz.android_greendao_sample.Course;
import com.example.lz.android_greendao_sample.StudentCourseRelation;

import com.example.lz.android_greendao_sample.dao.SimpleEntityDao;
import com.example.lz.android_greendao_sample.dao.ProvinceDao;
import com.example.lz.android_greendao_sample.dao.CityDao;
import com.example.lz.android_greendao_sample.dao.CustomTypeEntityDao;
import com.example.lz.android_greendao_sample.dao.KeepEntityDao;
import com.example.lz.android_greendao_sample.dao.PersonDao;
import com.example.lz.android_greendao_sample.dao.PersonInfoDao;
import com.example.lz.android_greendao_sample.dao.CustomerEntityDao;
import com.example.lz.android_greendao_sample.dao.OrderEntityDao;
import com.example.lz.android_greendao_sample.dao.StudentDao;
import com.example.lz.android_greendao_sample.dao.CourseDao;
import com.example.lz.android_greendao_sample.dao.StudentCourseRelationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig simpleEntityDaoConfig;
    private final DaoConfig provinceDaoConfig;
    private final DaoConfig cityDaoConfig;
    private final DaoConfig customTypeEntityDaoConfig;
    private final DaoConfig keepEntityDaoConfig;
    private final DaoConfig personDaoConfig;
    private final DaoConfig personInfoDaoConfig;
    private final DaoConfig customerEntityDaoConfig;
    private final DaoConfig orderEntityDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig courseDaoConfig;
    private final DaoConfig studentCourseRelationDaoConfig;

    private final SimpleEntityDao simpleEntityDao;
    private final ProvinceDao provinceDao;
    private final CityDao cityDao;
    private final CustomTypeEntityDao customTypeEntityDao;
    private final KeepEntityDao keepEntityDao;
    private final PersonDao personDao;
    private final PersonInfoDao personInfoDao;
    private final CustomerEntityDao customerEntityDao;
    private final OrderEntityDao orderEntityDao;
    private final StudentDao studentDao;
    private final CourseDao courseDao;
    private final StudentCourseRelationDao studentCourseRelationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        simpleEntityDaoConfig = daoConfigMap.get(SimpleEntityDao.class).clone();
        simpleEntityDaoConfig.initIdentityScope(type);

        provinceDaoConfig = daoConfigMap.get(ProvinceDao.class).clone();
        provinceDaoConfig.initIdentityScope(type);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        customTypeEntityDaoConfig = daoConfigMap.get(CustomTypeEntityDao.class).clone();
        customTypeEntityDaoConfig.initIdentityScope(type);

        keepEntityDaoConfig = daoConfigMap.get(KeepEntityDao.class).clone();
        keepEntityDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        personInfoDaoConfig = daoConfigMap.get(PersonInfoDao.class).clone();
        personInfoDaoConfig.initIdentityScope(type);

        customerEntityDaoConfig = daoConfigMap.get(CustomerEntityDao.class).clone();
        customerEntityDaoConfig.initIdentityScope(type);

        orderEntityDaoConfig = daoConfigMap.get(OrderEntityDao.class).clone();
        orderEntityDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        courseDaoConfig = daoConfigMap.get(CourseDao.class).clone();
        courseDaoConfig.initIdentityScope(type);

        studentCourseRelationDaoConfig = daoConfigMap.get(StudentCourseRelationDao.class).clone();
        studentCourseRelationDaoConfig.initIdentityScope(type);

        simpleEntityDao = new SimpleEntityDao(simpleEntityDaoConfig, this);
        provinceDao = new ProvinceDao(provinceDaoConfig, this);
        cityDao = new CityDao(cityDaoConfig, this);
        customTypeEntityDao = new CustomTypeEntityDao(customTypeEntityDaoConfig, this);
        keepEntityDao = new KeepEntityDao(keepEntityDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);
        personInfoDao = new PersonInfoDao(personInfoDaoConfig, this);
        customerEntityDao = new CustomerEntityDao(customerEntityDaoConfig, this);
        orderEntityDao = new OrderEntityDao(orderEntityDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        courseDao = new CourseDao(courseDaoConfig, this);
        studentCourseRelationDao = new StudentCourseRelationDao(studentCourseRelationDaoConfig, this);

        registerDao(SimpleEntity.class, simpleEntityDao);
        registerDao(Province.class, provinceDao);
        registerDao(City.class, cityDao);
        registerDao(CustomTypeEntity.class, customTypeEntityDao);
        registerDao(KeepEntity.class, keepEntityDao);
        registerDao(Person.class, personDao);
        registerDao(PersonInfo.class, personInfoDao);
        registerDao(CustomerEntity.class, customerEntityDao);
        registerDao(OrderEntity.class, orderEntityDao);
        registerDao(Student.class, studentDao);
        registerDao(Course.class, courseDao);
        registerDao(StudentCourseRelation.class, studentCourseRelationDao);
    }
    
    public void clear() {
        simpleEntityDaoConfig.getIdentityScope().clear();
        provinceDaoConfig.getIdentityScope().clear();
        cityDaoConfig.getIdentityScope().clear();
        customTypeEntityDaoConfig.getIdentityScope().clear();
        keepEntityDaoConfig.getIdentityScope().clear();
        personDaoConfig.getIdentityScope().clear();
        personInfoDaoConfig.getIdentityScope().clear();
        customerEntityDaoConfig.getIdentityScope().clear();
        orderEntityDaoConfig.getIdentityScope().clear();
        studentDaoConfig.getIdentityScope().clear();
        courseDaoConfig.getIdentityScope().clear();
        studentCourseRelationDaoConfig.getIdentityScope().clear();
    }

    public SimpleEntityDao getSimpleEntityDao() {
        return simpleEntityDao;
    }

    public ProvinceDao getProvinceDao() {
        return provinceDao;
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public CustomTypeEntityDao getCustomTypeEntityDao() {
        return customTypeEntityDao;
    }

    public KeepEntityDao getKeepEntityDao() {
        return keepEntityDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public PersonInfoDao getPersonInfoDao() {
        return personInfoDao;
    }

    public CustomerEntityDao getCustomerEntityDao() {
        return customerEntityDao;
    }

    public OrderEntityDao getOrderEntityDao() {
        return orderEntityDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public CourseDao getCourseDao() {
        return courseDao;
    }

    public StudentCourseRelationDao getStudentCourseRelationDao() {
        return studentCourseRelationDao;
    }

}
