package com.example.lz.android_greendao_sample.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.example.lz.android_greendao_sample.CustomerEntity;

import com.example.lz.android_greendao_sample.OrderEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ORDER_ENTITY".
*/
public class OrderEntityDao extends AbstractDao<OrderEntity, Long> {

    public static final String TABLENAME = "ORDER_ENTITY";

    /**
     * Properties of entity OrderEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property OrderID = new Property(0, Long.class, "orderID", true, "ORDER_ID");
        public final static Property Amount = new Property(1, Float.class, "amount", false, "AMOUNT");
        public final static Property CustomerID = new Property(2, Long.class, "customerID", false, "CUSTOMER_ID");
    };

    private DaoSession daoSession;

    private Query<OrderEntity> customerEntity_OrdersQuery;

    public OrderEntityDao(DaoConfig config) {
        super(config);
    }
    
    public OrderEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ORDER_ENTITY\" (" + //
                "\"ORDER_ID\" INTEGER PRIMARY KEY ," + // 0: orderID
                "\"AMOUNT\" REAL," + // 1: amount
                "\"CUSTOMER_ID\" INTEGER);"); // 2: customerID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ORDER_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OrderEntity entity) {
        stmt.clearBindings();
 
        Long orderID = entity.getOrderID();
        if (orderID != null) {
            stmt.bindLong(1, orderID);
        }
 
        Float amount = entity.getAmount();
        if (amount != null) {
            stmt.bindDouble(2, amount);
        }
 
        Long customerID = entity.getCustomerID();
        if (customerID != null) {
            stmt.bindLong(3, customerID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OrderEntity entity) {
        stmt.clearBindings();
 
        Long orderID = entity.getOrderID();
        if (orderID != null) {
            stmt.bindLong(1, orderID);
        }
 
        Float amount = entity.getAmount();
        if (amount != null) {
            stmt.bindDouble(2, amount);
        }
 
        Long customerID = entity.getCustomerID();
        if (customerID != null) {
            stmt.bindLong(3, customerID);
        }
    }

    @Override
    protected final void attachEntity(OrderEntity entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OrderEntity readEntity(Cursor cursor, int offset) {
        OrderEntity entity = new OrderEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // orderID
            cursor.isNull(offset + 1) ? null : cursor.getFloat(offset + 1), // amount
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // customerID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OrderEntity entity, int offset) {
        entity.setOrderID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAmount(cursor.isNull(offset + 1) ? null : cursor.getFloat(offset + 1));
        entity.setCustomerID(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OrderEntity entity, long rowId) {
        entity.setOrderID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OrderEntity entity) {
        if(entity != null) {
            return entity.getOrderID();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "orders" to-many relationship of CustomerEntity. */
    public List<OrderEntity> _queryCustomerEntity_Orders(Long customerID) {
        synchronized (this) {
            if (customerEntity_OrdersQuery == null) {
                QueryBuilder<OrderEntity> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.CustomerID.eq(null));
                customerEntity_OrdersQuery = queryBuilder.build();
            }
        }
        Query<OrderEntity> query = customerEntity_OrdersQuery.forCurrentThread();
        query.setParameter(0, customerID);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCustomerEntityDao().getAllColumns());
            builder.append(" FROM ORDER_ENTITY T");
            builder.append(" LEFT JOIN CUSTOMER_ENTITY T0 ON T.\"CUSTOMER_ID\"=T0.\"CUSTOMER_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected OrderEntity loadCurrentDeep(Cursor cursor, boolean lock) {
        OrderEntity entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        CustomerEntity customerEntity = loadCurrentOther(daoSession.getCustomerEntityDao(), cursor, offset);
        entity.setCustomerEntity(customerEntity);

        return entity;    
    }

    public OrderEntity loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<OrderEntity> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<OrderEntity> list = new ArrayList<OrderEntity>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<OrderEntity> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<OrderEntity> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
