package com.example.lz.android_greendao_sample;

import org.greenrobot.greendao.annotation.*;

import com.example.lz.android_greendao_sample.customtype.MyTimestamp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CUSTOM_TYPE_ENTITY".
 */
@Entity
public class CustomTypeEntity {

    @Id
    private Long id;

    @Convert(converter = com.example.lz.android_greendao_sample.customtype.MyTimestampConverter.class, columnType = Long.class)
    private MyTimestamp myCustomTimestamp;

    @Generated
    public CustomTypeEntity() {
    }

    public CustomTypeEntity(Long id) {
        this.id = id;
    }

    @Generated
    public CustomTypeEntity(Long id, MyTimestamp myCustomTimestamp) {
        this.id = id;
        this.myCustomTimestamp = myCustomTimestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public MyTimestamp getMyCustomTimestamp() {
        return myCustomTimestamp;
    }

    public void setMyCustomTimestamp(MyTimestamp myCustomTimestamp) {
        this.myCustomTimestamp = myCustomTimestamp;
    }

}
