package com.example.lz.android_greendao_sample;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "KEEP_ENTITY".
 */
@Entity
public class KeepEntity {

    @Id
    private Long id;
    private String type;
    private String name;

    // KEEP FIELDS - put your custom fields here
    private String keepField;
    // KEEP FIELDS END

    @Generated
    public KeepEntity() {
    }

    public KeepEntity(Long id) {
        this.id = id;
    }

    @Generated
    public KeepEntity(Long id, String type, String name) {
        this.id = id;
        this.type = type;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // KEEP METHODS - put your custom methods here

    public String getKeepField() {
        return keepField;
    }

    public void setKeepField(String keepField) {
        this.keepField = keepField;
    }
    // KEEP METHODS END

}
